import type { Finding, OverallVerdict } from "@/lib/types";

type ReportInput = {
  projectName: string;
  targetUrl: string;
  platform?: string | null;
  verdict: OverallVerdict;
  findings: Finding[];
  completedAt?: string;
  preview?: boolean;
};

export function findingsToMarkdown(report: ReportInput): string {
  const when = report.completedAt
    ? new Date(report.completedAt).toISOString()
    : new Date().toISOString();
  const verdictLabel = report.verdict === "at_risk" ? "AT RISK" : "SECURE";

  const lines: string[] = [
    `# ScanCraft inspection report`,
    ``,
    `| Field | Value |`,
    `| --- | --- |`,
    `| Project | ${escapeCell(report.projectName)} |`,
    `| URL | ${escapeCell(report.targetUrl)} |`,
    `| Platform | ${escapeCell(report.platform ?? "n/a")} |`,
    `| Scanned | ${when} |`,
    `| Verdict | **${verdictLabel}** |`,
    `| Mode | ${report.preview ? "Preview (limited checks)" : "Full scan"} |`,
    ``,
    `## Summary`,
    ``,
    `- Critical: ${count(report.findings, "critical")}`,
    `- Warning: ${count(report.findings, "warning")}`,
    `- Info: ${count(report.findings, "info")}`,
    `- Pass: ${count(report.findings, "pass")}`,
    ``,
    `## Findings`,
    ``,
  ];

  if (report.findings.length === 0) {
    lines.push(`_No findings recorded._`, ``);
  } else {
    const order = ["critical", "warning", "info", "pass"] as const;
    const sorted = [...report.findings].sort(
      (a, b) => order.indexOf(a.severity) - order.indexOf(b.severity)
    );

    for (const f of sorted) {
      lines.push(`### [${f.severity.toUpperCase()}] ${f.title}`);
      lines.push(``);
      lines.push(`- **Location:** \`${f.location}\``);
      lines.push(`- **Detail:** ${f.detail}`);
      if (f.evidence) {
        lines.push(``);
        lines.push(`\`\`\``);
        lines.push(f.evidence);
        lines.push(`\`\`\``);
      }
      if (f.fix) {
        lines.push(``);
        lines.push(
          `**Fix (${f.fix.type}):**`,
          ``,
          "```",
          f.fix.content,
          "```"
        );
      }
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(`_Generated by ScanCraft. Secrets in evidence are redacted._`);
  lines.push(``);

  return lines.join("\n");
}

function count(findings: Finding[], severity: Finding["severity"]) {
  return findings.filter((f) => f.severity === severity).length;
}

function escapeCell(value: string) {
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

export function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".md") ? filename : `${filename}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
